//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogViewer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\wpdevapppfc2016\\WY\\Logs")]
        public string OnlineLogFolderPath {
            get {
                return ((string)(this["OnlineLogFolderPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\WY\\Logs")]
        public string OfflineLogFolderPath {
            get {
                return ((string)(this["OfflineLogFolderPath"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MainWindowPlacement {
            get {
                return ((string)(this["MainWindowPlacement"]));
            }
            set {
                this["MainWindowPlacement"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowWelcomeNotification {
            get {
                return ((bool)(this["ShowWelcomeNotification"]));
            }
            set {
                this["ShowWelcomeNotification"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>\\WPDEVAPPPFC2016\WY\Logs</string>
  <string>\\mtkalapfc10\c$\ProgramData\Proficy\Logs</string>
  <string>\\mtkalasql10\c$\ProgramData\Proficy\Logs</string>
  <string>\\MTKALAPFC10\PROFICYLOGS</string>
  <string>\\MTKALASQL10\PROFICYLOGS</string>
  <string>\\wpdevapppfc2016\c$\programdata\proficy\logs</string>
  <string>\\wpdevsqlpfc2016\c$\programdata\proficy\logs</string>
  <string>\\wpdevapppfc02\c$\programdata\proficy\logs</string>
  <string>\\wpdevdbspfc02\c$\programdata\proficy\logs</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection LogFolderPaths {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["LogFolderPaths"]));
            }
            set {
                this["LogFolderPaths"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AddOfflineLogFolder {
            get {
                return ((bool)(this["AddOfflineLogFolder"]));
            }
            set {
                this["AddOfflineLogFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection LogFolderIsActiveBools {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["LogFolderIsActiveBools"]));
            }
            set {
                this["LogFolderIsActiveBools"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UpgradeLogFolderSettings {
            get {
                return ((bool)(this["UpgradeLogFolderSettings"]));
            }
            set {
                this["UpgradeLogFolderSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SettingsWindowPlacement {
            get {
                return ((string)(this["SettingsWindowPlacement"]));
            }
            set {
                this["SettingsWindowPlacement"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UpgradeSettings {
            get {
                return ((bool)(this["UpgradeSettings"]));
            }
            set {
                this["UpgradeSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>WPDEVSQLPFC2016</string>\r\n  <string>WPDEVDBSPFC02</string>\r\n</ArrayOfStrin" +
            "g>")]
        public global::System.Collections.Specialized.StringCollection DatabaseNames {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DatabaseNames"]));
            }
            set {
                this["DatabaseNames"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastVersionNumber {
            get {
                return ((string)(this["LastVersionNumber"]));
            }
            set {
                this["LastVersionNumber"] = value;
            }
        }
    }
}
